### ISSUE TITLE
Lower bound and upper bound in find_optimum_budget function can produce unintuitive result

### ISSUE THREAD

**Issue by yanhong-zhao-ef** [google/lightweight_mmm#83] opened 2022-10-03 14:26 UTC
Due to the slight differences between how _generate_starting_values and _get_lower_and_upper_bounds differ in calculating the budget allocated to each channel, when setting percentages lower bound or upper bound, it is hard for user to know what is the reference point.

For example in my case, a channel has 41% spend in starting_values with a 0 pct upper bound (we cannot scale this channel any further) can still produce a 52% allocation in the final solution due to the _get_lower_and_upper_bounds function referencing mean values for media data.

Is it better to pass in absolute values for lower and upper bound in this case? Or it is better for these two functions to use consistent calculation methodologies?

**Comment by pabloduque0** [comment] 2022-10-03 14:48
`_generate_starting_values` and `_get_lower_and_upper_bounds` differ in calculation by design. The optimisation itself works on "media unit" but the constraint within it needs to use the budget to make sure the constraint of "using all the budget" is met along the way. That is why the bounds are based on an average of historic media unit and the starting values include the budget in that calculation (also note that starting values dont really need to include budget and we only do that so we can provide the user an average value they can compare against after the optimisation, starting values could be random technically).

I think the current behaviour that you are finding is due to #82 (which should be fixed this week). The best thing is to ignore the third output on `optimize_media. find_optimal_budgets` and calculate yourself some average budget you want to compare against.

Since the prices and bounds are both per channel calculating the bounds in monetary value and then converting back to media unit, or calculating them in media unit directly should yield the same result.

Let me know if Im somehow miss-understanding the issue you are finding.

**Closed** 2022-10-03 17:49 UTC
Labels: question
